### ISSUE TITLE
Options page sometimes shows white text on white background

### ISSUE THREAD

**Issue by irrationalpie7** [BrickGrass/Blanket-Permission-Highlighter#11]
While trying to adjust the highlight color recently, I noticed that the options page was displaying as white text on a white background for me. I suspect the issue is to do with the AO3 site skin that I use to have dark mode on AO3 (I've made some tweaks, but the colors are all the same as in the public [Reversi](https://archiveofourown.org/skins/929) skin). When I stopped using [Reversi](https://archiveofourown.org/skins/929), the pop-up had black text on a white background, as presumably intended. I suspect this issue impacts anyone who uses a site skin to view AO3 in dark or dark-ish mode. Let me know if there's any other info I can provide!

In case it's relevant, I was using the highlighter via tampermonkey on chrome when I encountered this issue. I've included some screen caps below:

Options pop-up with text highlighted so that it's readable
![Options pop-up with text highlighted so that it's readable](https://user-images.githubusercontent.com/76858438/163352763-9d42bf98-61af-4d77-8507-dc0877f56748.png)

Options pop-up with white text on white background
![Options pop-up with white text on white background](https://user-images.githubusercontent.com/76858438/163352791-07f777b9-b43e-4399-87de-381fceab528d.png)

Options pop-up with normal contrast after turning off the [Reversi](https://archiveofourown.org/skins/929) skin.
![Options pop-up with normal contrast](https://user-images.githubusercontent.com/76858438/163354008-f6622098-e410-4e0c-b490-eef2493c427c.png)

**Comment by BrickGrass** [comment]
Thanks for letting me know! I seem to have enforced a white background but not a specific text colour, oops. I'll either enforce black text as well, or see if I can figure out how to get the theme to act on the pop-up properly.

**Comment by BrickGrass** [comment]
All fixed! I decided to enforce black text, links, etc.
