### ISSUE TITLE
Wrong highlight

### ISSUE THREAD

**Issue by Literarion** [BrickGrass/Blanket-Permission-Highlighter#17]
Hi,
I've been using the highlighter for a while now and love it. Today I noticed that suddenly my own account got highlighted as well - which it never was before, and really should not be, because a) I do not give blanket permission and do not want to, and b) my account is not listed on the source list! 
See example here: https://archiveofourown.org/works/40579158/chapters/101665212
![image](https://user-images.githubusercontent.com/120274275/206869451-88d008fa-b9e2-4394-a7b3-681fd5e8fda8.png)
And reference here 
![image](https://user-images.githubusercontent.com/120274275/206869479-b7e83f9a-ffe2-4928-8b12-625cf528dbd0.png)

**Comment by BrickGrass** [comment]
Hi, there was a brief bug yesterday that had all usernames being marked as having bp in the cache. It's fixed now, so if you clear your cache (turn the Enable Storage/Caching setting off, and then on again) it should fix itself. Or just wait 24 hours from when your username was first highlighted, the incorrect data will just clear after that time

<img width="335" alt="image" src="https://user-images.githubusercontent.com/49255229/206912025-a7ed222b-aa11-4b9b-aacd-ae101a17896a.png">
<img width="560" alt="image" src="https://user-images.githubusercontent.com/49255229/206912035-dec1feda-a3ae-4045-9de3-8ea4eae779ef.png">
