### ISSUE TITLE
Pseuds are green, but not always on profile page

### ISSUE THREAD

**Issue by teapot81** [BrickGrass/Blanket-Permission-Highlighter#19]
- On a user's profile page, pseuds are occasionally, but often not, green. See:

>  <img width="527" alt="Screenshot 2024-03-21 at 09 20 03" src="https://github.com/BrickGrass/Blanket-Permission-Highlighter/assets/81442218/5a561669-cd8b-4d2d-aca3-c8c81f298bb5">

- This is another user's profile, where they are partially green:

>  <img width="668" alt="Screenshot 2024-03-21 at 09 27 06" src="https://github.com/BrickGrass/Blanket-Permission-Highlighter/assets/81442218/af306376-18f5-41f4-8e9d-a50a2c1bab62">

- And finally, here is an example of a page where all pseuds are rightfully green:

>  <img width="591" alt="Screenshot 2024-03-21 at 13 45 55" src="https://github.com/BrickGrass/Blanket-Permission-Highlighter/assets/81442218/80a0eef8-bd8c-48a0-833c-6b83995c5cff">

- However on the pseud's works page, they appear to be always green:

>  <img width="841" alt="Screenshot 2024-03-21 at 09 20 20" src="https://github.com/BrickGrass/Blanket-Permission-Highlighter/assets/81442218/93bfdfe8-2cdc-460a-87ab-65367ceccbe3">

I wanted to highlight this discrepancy to you. I made the assumption that the black names were because some pseuds had BP but other pseuds didn't, but on checking with how fpslist functions, I realise this is some sort of bug.

Thank you for all that you do. It's a spiffing extension!

**Comment by BrickGrass** [comment]
Sorry, I seem to have completely missed this ticket! I can reproduce this, I'll take a look at fixing the issue soon :)
